[project]
name = "klasna"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tanjiro", email = "viktor1svider@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "httpx2>=2.9.1",
    "sqlmodel>=0.0.39",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit",
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff",
]

[tool.pyright]
include = ["src"]
typeCheckingMode = "strict"
pythonPlatform = "All"

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v --cov=src"
