[project]
name = "klasna"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tanjiro", email = "viktor1svider@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "httpx2>=2.9.1",
    "sqlmodel>=0.0.39",
]

[project.scripts]
klasna = "klasna:main"

[tools.uv.scripts]
dev = "fastapi dev"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]
